export const countryList = [
  { label: 'Austria', value: 'AT' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Cyprus', value: 'CY' },
  { label: 'Czech Republic', value: 'CZ' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Germany', value: 'DE' },
  { label: 'Estonia', value: 'EE' },
  { label: 'Greece', value: 'EL' },
  { label: 'Greece', value: 'GR' },
  { label: 'Spain', value: 'ES' },
  { label: 'Finland', value: 'FI' },
  { label: 'France', value: 'FR' },
  { label: 'Croatia', value: 'HR' },
  { label: 'Italy', value: 'IT' },
  { label: 'Latvia', value: 'LV' },
  { label: 'Lithuania', value: 'LT' },
  { label: 'Luxembourg', value: 'LU' },
  { label: 'Hungary', value: 'HU' },
  { label: 'Ireland', value: 'IE' },
  { label: 'Malta', value: 'MT' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'Poland', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Romania', value: 'RO' },
  { label: 'Slovenia', value: 'SI' },
  { label: 'Slovakia', value: 'SK' },
  { label: 'Sweden', value: 'SE' },
  { label: 'United Kingdom', value: 'UK' },
  { label: 'United Kingdom', value: 'GB' },
]
